version: '2'
services:
    stufi-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/stufi/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=stufi
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
